services:
  evansdale_pizza:
    container_name: evansdale_pizza_app
    build:
      context: ./app 
    ports:
      - "7100:5000"
    volumes:
      - ./app/orders:/app/orders
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    networks:
      - evansdale_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=evansdale_pizza
    networks:
      - evansdale_net

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express_gui
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}  # Read from .env
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    env_file:
      - stack.env
    ports:
      - "7101:8081"
    depends_on:
      - mongodb
    networks:
      - evansdale_net

volumes:
  app_data:
  mongo_data:

networks:
  evansdale_net:
    driver: bridge
